### ISSUE TITLE
English in calendar is stayed

### ISSUE THREAD

**Issue by truefriend-cz** [mstojanovv/PerfexCRM#122]
BUG: After the client logs in to his section, the calendar is displayed in English, even though he has selected other language.
Tested on version 2.9.1

**Comment by mstojanovv** [comment]
Hi.

Please open a support ticket at https://my.perfexcrm.com as we don't provide support here.

Regards.

**Comment by truefriend-cz** [comment]
I dont have account. And account is only for payed customers.
And bug login... if click on green button "Login with Envato account"then ended error 500.
Before buy this script i testing from https://github.com/Jedi0x/perfexcrm
When the bugs are fixed, I assume that I will purchase the script.
