### ISSUE TITLE
Leftover misspelled keys

### ISSUE THREAD

**Issue by TheZoker** [mstojanovv/PerfexCRM#19]
| Line | False Key                                    | Right Key                                     |
|------|----------------------------------------------|-----------------------------------------------|
| 768  | staff_edit_profile_change_repet_new_password | staff_edit_profile_change_repeat_new_password |
| 2351 | announcements_recents                        | announcements_recent                          |
| 3049 | readibility                                  | readability                                   |
| 3313 | form_informations                            | form_information                              |

**Comment by mstojanovv** [comment]
Adjusted in v.1.7.0.
