### ISSUE TITLE
Need Arabic language for this perfexCRM

### ISSUE THREAD

**Issue by 0568595** [mstojanovv/PerfexCRM#63]
Need Arabic language for this perfexCRM . 

please create one for us . 

thanks

**Comment by mstojanovv** [comment]
Hello.

There is no Arabic translation, someone needs to contribute the translation, we can't just create it as we don't speak Arabic.

Feel free to test on the demo to see if Perfex CRM is suitable for your needs.

Regards.

**Comment by 0568595** [comment]
Hello

Yes Sure I can contribute the translation . 

You Just send me the file and i'll contribute the translation .

**Comment by m5lil** [comment]
https://codecanyon.net/item/perfex-crm-arabic-language-translation-pack/27276027

**Comment by GHO5TMEDO** [comment]
> https://codecanyon.net/item/perfex-crm-arabic-language-translation-pack/27276027

This translation is not correct at all! Please improve.
