### ISSUE TITLE
Update Slovak lang 2.3.5

### ISSUE THREAD

**Issue by grafitek** [mstojanovv/PerfexCRM#72]
Update Slovak lang 2.3.5
[slovak_lang.zip](https://github.com/mstojanovv/PerfexCRM/files/3265943/slovak_lang.zip)

**Comment by mstojanovv** [comment]
Thanks.

I updated the repository, here is the commit: https://github.com/mstojanovv/PerfexCRM/commit/3c0ea80748a7f86a17084bfd4cdaee6a386ac355

Regards.
