### ISSUE TITLE
Default SMS doesn't work

### ISSUE THREAD

**Issue by shyamshanbhag** [mstojanovv/PerfexCRM#81]
Can anyone sort the SMS send issue when configured with MSG91 SMS Platform.. rest all configurations are working fine.. but my clients won't get SMS notification.. but the email notification is working fine

Thanks in advance..

**Comment by mstojanovv** [comment]
This is the Perfex CRM language repository, please open a support ticket at https://support.perfexcrm.com we will be happy to guide you.
